#!/bin/bash
NAME
	holberton - become a full-stacksoftware engineer.

SYNOPSIS
	holberton [STUDENTNAME]

DESCRIPTION
	Holberton School is a project-based alternative to college for the next generation of software engineers.

OPTIONS
	holberton does not take any options. However, you can supply studentname.

SEE ALSO
	peerlearning(2), projectbased(2), fullstack(2), Betty(1)

BUGS
	No known bugs.

AUTHOR
	Julien Barbier, Sylvian Kalache, Sophie Barbier, Guillaume Salva, Kris Bredemeier, Julien Cyr, Alex Gautier and all the Holberton mentors