#!/usr/bin/env bash
#Displays memes on signals

echo $$ >> /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
