#!/usr/bin/env bash
# goodole fizzbuzz
buzzer=(ph Fizz Buzz FizzBuzz)
for ((count=1;count<=100;count++)); do
    (( number=(count % 3 == 0) + (2 * (count % 5 == 0 )) ))
    if (( number == 0 )); then
       	  echo "$count"
    else
	echo ${buzzer[$number]}
    fi
done