#!/usr/bin/env bash
#Fill given prompt
while IFS=":" read USER PW UID INFO HOME INFO
do
    echo "The user $USER is part of the $GID gang, lives in $HOME and rides $CMD. $UID's place is protected by the passcode $PW, more info about the user here: $INFO"
done < /etc/passwd