#!/usr/bin/env bash
#Fill given prompt
while IFS=: read -r user pw uid info home cmd
do
    echo "The user $user is part of the #gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pw, more info about the user here: $info"
done < /etc/passwd