#!/usr/bin/env bash
# Prints Holberton School X10, on 9 print Hi
count=0
while [ $count -lt 10 ]; do
      echo "Holberton School"
      if (( count == 8 )); then
      	    echo "Hi"
      fi
      (( count++ ))
done
