#!/usr/bin/env bash
#Build a clock
hour=0
minute=1
while [ $hour  -le 12 ]
do
    echo "Hour: $hour"
    let minute=1
    while [ $minute -le 59 ]
    do
        echo "$minute"
	let minute=minute+1
    done
    let hour=hour+1
done
