#!/usr/bin/env bash
#Print info about holbertonschool file
betty="./holbertonschool"
if [ -e "$betty" ]
then
    echo "holbertonschool file exists"
    if [ -s "$betty" ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f "$betty" ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
